sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
notifications:
  email: false
git:
  depth: 5
cache:
  timeout: 600
  directories:
    - ${HOME}/.cargo
    - ${TRAVIS_BUILD_DIR}/target
stages:
  - Check
  - CheckMore
  - Build
  - Test
jobs:
  include:

    - stage: Check
      name: Format
      install: travis_wait make install-format-check
      before_script: cargo fmt --version
      script: make format-check

    - stage: Check
      name: Dependencies
      script: make deps-check

    - stage: CheckMore
      name: Lint
      install: travis_wait make install-lint-check
      before_script: cargo clippy --version
      script: make lint-check

    - stage: CheckMore
      name: Security
      install: travis_wait make install-security-check
      before_script: cargo audit --version
      script: make security-check

    - stage: Build
      name: Build
      script: make build

    - stage: Test
      name: UnitTest
      script: make test

    - stage: Test
      name: Bench
      script: make bench || true
