[package]
name = "fibonacci-macros"
version = "0.1.0"
authors = ["YangBy <yby@yangby.org>"]

[dependencies]
syn = "0.14"
quote = "0.6"
proc-macro2 = "0.4"
fibonacci-functions = { path = "../functions" }

[lib]
proc-macro = true
